Add gradient map filter
mltframework/mlt pull request #1046
Opened 2024-11-02 19:46 UTC by YakoYakoYokuYoku

Add a new filter for gradient mapping.

`filter_gradientmap` takes a frame and maps the intensity of its color to a linear gradient denoted by a list of color and position pairs separated by semicolons. Inspired by the Color Ramp node from Blender and the Gradient Map operation from image editors such as GIMP's and Krita's.

2024-11-02 19:56 UTC, bmatherly commented
Some other filters already have a method for specifying color stops for a gradient. Could that method work for you? If so, it would be nice to be consistent.
Here is an example:
https://github.com/mltframework/mlt/blob/335d0093dc5220466f49f7d307dca7bfc9d08e32/src/modules/qt/filter_lightshow.yml#L65

2024-11-02 21:19 UTC, YakoYakoYokuYoku commented
I've tried looking into other filters but I couldn't notice how `filter_lightshow` does it, I thought it was in no way possible. Thanks for the tip.

2024-11-03 17:23 UTC, YakoYakoYokuYoku commented
Formatted the code with clang-format. I've preferred to use `std::map` instead of `mlt_cache` because the latter doesn't have a way to get objects by their key value. I'll add a demo to the PR comment to show what the filter can do.

2024-11-04 02:30 UTC, bmatherly commented
I had to create this patch to get this code to compile.
[gradientmap.diff.txt](https://github.com/user-attachments/files/17613205/gradientmap.diff.txt)

> I've tried looking into other filters but I couldn't notice how filter_lightshow does it

Your implementation does not match the other filters because each color has two parts - the color and the position. Combining the values makes it more difficult for applications to use this API. Can you get by without the position? The other filters that use this method make the colors equally spaced - so a stop position is not required.

2024-11-04 03:04 UTC, bmatherly commented
Did you check the list of filters we get from Frei0r and avfilter to see if one of them already provide this effect?

Here is a screenshot of the UI in Shotcut for the existing gradient method. If you can switch this filter to use the same method, then the code in Shotcut would be easily reused to add a UI for it.

![image](https://github.com/user-attachments/assets/fd6b33e6-311c-4407-a6c4-dc07cf6a3302)

2024-11-06 01:00 UTC, YakoYakoYokuYoku commented on src/modules/plus/filter_gradientmap.cpp
> +        while (--i) {
I've seen that some other filters used backwards loops and I thought it was correct. I've changed the loop to reflect what you've said.

2024-11-06 01:00 UTC, YakoYakoYokuYoku commented on src/modules/plus/filter_gradientmap.cpp
> +struct mlt_gradient
Took notice of it.

2024-11-06 01:04 UTC, YakoYakoYokuYoku commented on src/modules/plus/filter_gradientmap.cpp
> +    float intensity = (r * 0.30 + g * 0.59 + b * 0.11) / 255;
From the looks of it those color weights are the same but rounded from Rec. 601, so I'm not that far away. Still, I could implement support for YUV frames if desired.

2024-11-06 02:35 UTC, YakoYakoYokuYoku commented
> Your implementation does not match the other filters because each color has two parts - the color and the position. Combining the values makes it more difficult for applications to use this API.

From my point of view I don't think that combining a color and a position into a pair would be too difficult, YMMV.

> Can you get by without the position? The other filters that use this method make the colors equally spaced - so a stop position is not required.

I'm afraid to tell that positioning is required for the gradient stops, if not some gradient configurations would be very difficult to replicate with equidistant stops. For instance in a gradient widget that controls its stops with slides if two slidables were too close it'd require lots of their equidistant counterparts to represent the same gradient, not even mentioning of what happens with even more sliders.

> Did you check the list of filters we get from Frei0r and avfilter to see if one of them already provide this effect?

They do provide effects that involve gradients, but those are for overlays not mapping. The filter that resembles what gradient mapping does is `rgblut`, but that only works per RGB channel not by source intensity.

> Here is a screenshot of the UI in Shotcut for the existing gradient method. If you can switch this filter to use the same method, then the code in Shotcut would be easily reused to add a UI for it.

It can reuse the same widget if it supports slidable stops, else it could be modified or subclassed to suit this need.

2024-11-06 13:39 UTC, bmatherly commented
> I'm afraid to tell that positioning is required for the gradient stops, if not some gradient configurations would be very difficult to replicate with equidistant stops. For instance in a gradient widget that controls its stops with slides if two slidables were too close it'd require lots of their equidistant counterparts to represent the same gradient, not even mentioning of what happens with even more sliders.

OK. I will not require that you implement the fixed stop positions. But then lets rename this parameter so that all the color.* parameters in MLT will have the exact same interface. I suggest to rename "color.*" to "stop.*". Someone could add the "color.*" parameter as an alternate to the stop parameter. Bonus points if you also implement the fixed stop method as "color.*" as an alternate method to specify the gradient :)

> It can reuse the same widget if it supports slidable stops, else it could be modified or subclassed to suit this need.

I understand that is possible, but I think it is unlikely that a volunteer will come along to do that.

2024-11-17 19:27 UTC, ddennedy requested changes

2024-11-17 19:27 UTC, ddennedy commented on src/modules/plus/filter_gradientmap.cpp
> +        sprintf(name, "color.%d", i);
Please change the property name to `"stop.%d"` and update the YAML.

2024-11-17 19:27 UTC, ddennedy commented on src/modules/plus/filter_gradientmap.yml
> +          color.1='0xff000000 0.0' color.2='0xffffffff 1.0'
CSS style color specifications are now preferred in examples, but that is not a required change. I leave the choice to you.

2024-11-26 18:25 UTC, ddennedy commented
Just fix these minor compile errors (debug build uses `-Werror` with some exceptions), and I will merge it. Looks good, nice addition!
```
/home/runner/work/mlt/mlt/src/modules/plus/filter_gradientmap.cpp: In function ‘int filter_get_image(mlt_frame, uint8_t**, mlt_image_format*, int*, int*, int)’:
/home/runner/work/mlt/mlt/src/modules/plus/filter_gradientmap.cpp:236:18: error: unused variable ‘p’ [-Werror=unused-variable]
  236 |         uint8_t *p = *image;
      |                  ^
/home/runner/work/mlt/mlt/src/modules/plus/filter_gradientmap.cpp: In function ‘mlt_filter_s* filter_gradientmap_init(mlt_profile, mlt_service_type, const char*, char*)’:
/home/runner/work/mlt/mlt/src/modules/plus/filter_gradientmap.cpp:275:24: error: unused variable ‘properties’ [-Werror=unused-variable]
  275 |         mlt_properties properties = MLT_FILTER_PROPERTIES(filter);
      |                        ^~~~~~~~~~
```

2024-11-26 19:27 UTC, YakoYakoYokuYoku commented
> Just fix these minor compile errors (debug build uses `-Werror` with some exceptions), and I will merge it. Looks good, nice addition!
> 
> ...

I've ran the file with `clang-tidy` in my test setup but forgot to remove those unused variables here ... oops! Though, thanks for pointing it up.

2024-11-26 19:46 UTC, merged

2024-11-26 20:25 UTC, YakoYakoYokuYoku commented
Great! Thanks for the merge! I'll try to see if there's a chance to use `mlt_cache` instead of `std::map` for memoizing the gradient colors and if other color spaces can be used directly instead of converting them. I'll also try to implement support for it in Shotcut, though I'm not familiar with it, so I'll see.