Make color params of filters animatable
mltframework/mlt pull request #836
Opened 2022-10-30 12:36 UTC by jlskuz

Depends on #828

Affects color params of
- frei0r.*
- qttext
- qtcrop
- gpsgraphics
- audiolevelgraph
- audiospectrum
- audiowaveform

Affects all params of
- chroma
- chroma_hold

2022-10-30 20:41 UTC, bmatherly commented
LGTM

2022-11-02 07:07 UTC, ddennedy requested changes
Rebase this after #828 is merged

2022-11-03 08:21 UTC, jlskuz commented
Rebase done

2022-11-11 06:25 UTC, ddennedy approved these changes

2022-11-11 06:26 UTC, merged