Fix Chains incorrectly applying deinterlace link on invalid producers
mltframework/mlt pull request #918
Opened 2023-05-17 06:40 UTC by j-b-m

link_deinterlace was incorrectly attached to INVALID xml producers (the producers with a missing source on load), resulting in corrupted frames and possible crashes.

This can be reproduced with this command:
`melt -chain qtext:+INVALID`

With my fix, it now produces a correct image

2023-05-17 11:45 UTC, bmatherly requested changes

2023-05-17 16:46 UTC, j-b-m commented on src/modules/xml/producer_xml.c
> +                mlt_properties_set_int(properties, "progressive", 1);
Yes good idea. This is using the qtext producer, not the filter, but you are right. The progressive flag in qtext was set on the frame but not on the producer. I updated the patch accordingly and it fixes the problem.

2023-05-17 17:05 UTC, bmatherly commented on src/modules/xml/producer_xml.c
> +                mlt_properties_set_int(properties, "progressive", 1);
Thanks. Looks good. While we are on the topic, would you be willing to also check other image producers: pixbuf, pango, qtext, etc?

2023-05-17 17:24 UTC, ddennedy commented
"meta.media.progressive" is preferred now on producers over the bare "progressive". Both should not be needed as of a few years unless there is a new bug elsewhere.

2023-05-17 20:22 UTC, j-b-m commented
Ok, I have now changed the flag on producers to meta.media.progressive, and it seems to work correctly

2023-05-17 22:43 UTC, ddennedy approved these changes

2023-05-18 02:47 UTC, bmatherly approved these changes

2023-05-18 02:47 UTC, merged

2023-05-18 02:48 UTC, bmatherly commented
This is a good change. Thank you.