Playlist seam
mltframework/mlt pull request #923
Opened 2023-06-14 03:24 UTC by bmatherly

Add two "track only" filters to attempt to smooth discontinuities between clips in a playlist.

Before:
![image](https://github.com/mltframework/mlt/assets/821968/853b0069-4322-4fae-8ff7-6d6e1591f00c)

Auto Fade applied:
![image](https://github.com/mltframework/mlt/assets/821968/9893bf04-de56-470b-a08c-ef52b20ed839)

Seam applied:
![image](https://github.com/mltframework/mlt/assets/821968/e0586214-64e7-46b6-b3ef-ffd4ba9f1620)

The seam can produce perceptibly seamless splices in content with many frequencies. But it can cause destructive noise in calculated content like a sine wave.

2023-06-22 18:34 UTC, ddennedy requested changes

2023-06-22 18:34 UTC, ddennedy commented on src/framework/mlt_playlist.c
> +        mlt_properties_set_int(properties, "meta.playlist.clip_position", clip_position);
Please document the new properties in `mlt_playlist.h`.

2023-06-22 18:34 UTC, ddennedy commented on src/modules/core/filter_audioseam.yml
> +
The yaml is invalid missing a `parameters` key.

2023-06-22 18:34 UTC, ddennedy commented on src/modules/core/filter_autofade.yml
> +  - identifier: fade_duration
The yaml is invalid missing a `parameters` key.

2023-06-24 21:25 UTC, merged

2023-06-25 00:36 UTC, bmatherly commented
I see you made a commit to resolve your own comments. Thanks for doing that. Much appreciated.