GPS text: added grade, cadence, temperature + some small updates
mltframework/mlt pull request #934
Opened 2023-07-25 23:13 UTC by dany123

I have a quick note about the re-formatting rules: in the long if..else if chains with multiple lines of code inside each if block it absolutely needs a newline somewhere between each if block otherwise the entire chain looks like a huge blob of text and finding something is harder than it needs to be (see the code below line 281 in the first diff below). 
For short blocks it does look nice and cozy but those are readable no matter how you write them.

2023-07-25 23:21 UTC, ddennedy commented
> looks like a huge blob of text

Maybe this is a sign that you need to refactor into more functions. You can also add comment lines as headings for sections of code perhaps followed by an empty line.

2023-07-25 23:31 UTC, dany123 commented
Comments to group some of these does sound a pretty good workaround; I'm not sure refactoring further would be a good idea, the code would be too scattered (in this particular case).

2023-07-27 02:54 UTC, ddennedy requested changes

2023-07-27 02:54 UTC, ddennedy commented on src/modules/qt/filter_gpstext.cpp
> +		if (strstr(keyword, "RAW")) {
This is formatted badly. We do not use tabs any more for indent. We never really wanted expressions crammed together (spaces before and after operators). Please reformat it using `clang-format` version 14.

2023-07-27 02:54 UTC, ddennedy commented on src/modules/qt/filter_gpstext.cpp
> +			snprintf(gps_text, 10, "%.0f", crt_point.cad);
One thing clang-format does not enforce is matching usage of curly braces. I prefer that if the `if` block has curly braces so should each other block such as `else` here.

2023-07-28 19:59 UTC, merged